package com.example.proyect.demo.infrastructure.utils.enums;

public enum RolePermissionEnum {
    READ_ALL_EMPRESAS,
    READ_ONE_EMPRESA,
    CREATE_ONE_EMPRESA,
    UPDATE_ONE_EMPRESA,
    DISABLE_ONE_EMPRESA,

    READ_ALL_TIPOSEMPRESAS,
    READ_ONE_TIPOEMPRESA,
    CREATE_ONE_TIPOEMPRESA,
    UPDATE_ONE_TIPOEMPRESA,
    DISABLE_ONE_TIPOEMPRESA, 
    READ_MY_PROFILE, 
    UPDATE_ONE_PAIS

}